name: EDA Regression

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout framework
        uses: actions/checkout@v4
        with:
          path: eda-regression-framework

      - name: Checkout RISC-V Pipeline
        uses: actions/checkout@v4
        with:
          repository: ayushgupta-15/rv32i-5stage-pipelined-processor # Update to actual GitHub repository path
          path: riscv-pipeline
          
      - name: Checkout AXI4-Lite
        uses: actions/checkout@v4
        with:
          repository: ayushgupta-15/axi4-lite-interconnect-sv # Update to actual GitHub repository path
          path: axi4-lite-interconnect-sv
          
      - name: Checkout Serial Protocol
        uses: actions/checkout@v4
        with:
          repository: ayushgupta-15/serial-protocol-library # Update to actual GitHub repository path
          path: serial-protocol-library

      - name: Install Simulator Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog verilator

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Requirements
        run: |
          cd eda-regression-framework
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare Repositories
        run: |
          mkdir -p serial-protocol-library/sim
          mkdir -p serial-protocol-library/sim/waves

      - name: Run All Tests
        run: |
          cd eda-regression-framework
          python -m src.cli run-all || exit 0

      - name: Publish Regression Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: regression-report
          path: eda-regression-framework/reports/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: always()

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: eda-regression-framework/reports/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: run-regression
    if: always()
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
